### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by wfa207** [wfa207/downtime#7]
### Primary Colors
- .primary-0 { background-color: #48BBEC }
- .primary-1 { background-color: #A1DDF8 }
- .primary-2 { background-color: #6FCBF2 }
- .primary-3 { background-color: #23A9E3 }
- .primary-4 { background-color: #0796D3 }
### Complementary Colors
- .complement-1 { background-color: #FFD3A1 }
- .complement-2 { background-color: #FFBB6F }
- .complement-0 { background-color: #FFA745 }
- .complement-3 { background-color: #FF941D }
- .complement-4 { background-color: #FF8700 }
  ​

**Comment by jonrim** [comment]
Black backgrounds with Light blue text/lines

**Comment by wfa207** [comment]
Love it

**Comment by wfa207** [comment]
maybe Dark gray for backgrounds and then black for the navbars
